### ISSUE TITLE
digicam-spe does not work

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/digicampipe#172]
I made the input file `dark_digicamtoy_100evts.hdf5 ` with digicamtoy (master branch): `dark.yml` (only 100 events)

call looks like this:
    
    (digicampipe) dneise@lair:~/sst_new$ 
    digicam-spe --compute testfoo.hdf5 dark_digicamtoy_100evts.hdf5 

output: 
```
Traceback (most recent call last):
  File "/home/dneise/anaconda3-5.1.0/envs/digicampipe/bin/digicam-spe", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-spe')()
  File "/home/dneise/sst_new/digicampipe/digicampipe/scripts/spe.py", line 703, in entry
    main(args)
  File "/home/dneise/sst_new/digicampipe/digicampipe/scripts/spe.py", line 565, in main
    spe_charge, spe_amplitude = build_spe(events, max_events)
  File "/home/dneise/sst_new/digicampipe/digicampipe/scripts/spe.py", line 447, in build_spe
    for i, event in tqdm(zip(range(max_events), events), total=max_events):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by dneise** [comment]
There is a fix in PR #173
